Vagrant.configure(2) do |config|

    boxes = [
      { :name => "ubuntu-test-box", :box => "ubuntu/trusty64" },
      { :name => "ubuntu-test-box", :box => "ubuntu/trusty64" }
    ]

     boxes.each do |opts|
            config.vm.define opts[:name] do |config|
            config.vm.box = opts[:box]
            config.vm.hostname = VM_NAME
            # Set VM name in Virtualbox
            config.vm.provider "virtualbox" do |v|
                v.name = VM_NAME
                v.memory = 2048
            end

			config.vm.provision "shell", inline: <<-SHELL
				apt-get update && apt-get install -y unzip && rm -rf /var/lib/apt/lists/*

				# Install tools.
				apt install cmake git -y

				# General library dependencies.
				apt install libyaml-dev libjson-c-dev libxml2-dev libsdl2-dev libglew-dev libvulkan-dev libgl1-mesa-dev opencl-headers libzip-dev libfswatch-dev libfreeimage-dev libavcodec-dev libavfilter-dev libavformat-dev  libassimp-dev libfreetype6-dev -y
				# Audio and physic library dependencies.
				apt install libopenal-dev libbullet-dev -y
				# Editor library dependencies.
				apt install libgtk-3-dev
			SHELL

			config.vm.provision "shell", run:"always", privileged:false, inline: <<-SHELL
                mkdir -p build/
                cd build/
                cmake --build ./..
                make
                test/assert/fragview-assert

                # Run the testing.
            SHELL

            config.vm.provider :libvirt do |domain|
                domain.driver = "qemu"
                domain.memory = 512
                domain.cpus = 1
            end
        end
    end
end