INCLUDE(ExternalProject)

SET(FFMPEG_DIR ${CMAKE_CURRENT_BINARY_DIR}/libFFMPEG/source)
SET(FFMPEG_BIN ${CMAKE_CURRENT_BINARY_DIR}/libFFMPEG)
SET(FFMPEG_LIB ${FFMPEG_BIN}/lib/libffmpeg.a)
SET(FFMPEG_INCLUDE_DIRS ${FFMPEG_BIN}/include)

FILE(MAKE_DIRECTORY ${FFMPEG_INCLUDE_DIRS})

ExternalProject_Add(
  libFFMPEG
  GIT_REPOSITORY "https://github.com/FFmpeg/FFmpeg.git"
  GIT_TAG "n3.0"
  PREFIX ${FFMPEG_BIN}
  SOURCE_DIR ${FFMPEG_DIR}
  CONFIGURE_COMMAND ${FFMPEG_DIR}/configure --srcdir=${FFMPEG_DIR} --prefix=${FFMPEG_BIN} --enable-static --enable-static=yes --disable-shared  CFLAGS=-fPIC CXXFLAGS=-fPIC
  BUILD_COMMAND make
  UPDATE_DISCONNECTED True
  COMMENT           "Building ffmpeg"
  BUILD_BYPRODUCTS ${FFMPEG_LIB}
)

ADD_LIBRARY(ffmpeg STATIC IMPORTED)

ADD_DEPENDENCIES(ffmpeg libFFMPEG)

SET_TARGET_PROPERTIES(ffmpeg PROPERTIES IMPORTED_LOCATION ${FFMPEG_LIB})
SET_TARGET_PROPERTIES(ffmpeg PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${FFMPEG_INCLUDE_DIRS})
