name: FragCore Linux
on:
  push:
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        platform: [x32, x64]
        compiler: [gcc, clang]
        include:
        - os: ubuntu-20.04
          platform: x64
          compiler: clang
        - os: ubuntu-20.04
          platform: x32
          compiler: clang
        - os: ubuntu-20.04
          platform: x64
          compiler: gcc
        - os: ubuntu-20.04
          platform: x32
          compiler: gcc
    name: Linux FragCore Library ${{ matrix.os }} ${{ matrix.platform }}  ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Configure dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++-10 pkg-config libsdl2-dev libfreeimage-dev libssl-dev
          sudo apt-get install libsdl2-dev libvulkan-dev libgl1-mesa-dev opencl-headers \
          libgtest-dev libsubunit-dev libogg-dev libopus-dev libvorbis-dev \
          libzip-dev libopenal-dev mesa-common-dev ocl-icd-opencl-dev libnoise-dev libvdpau-dev \
          libalut-dev libspdlog-dev libbz2-dev libcurl4 libcurl4-gnutls-dev libfmt-dev binutils-dev libeigen3-dev \
          zip gzip googletest

      - name: Configure modules dependencies
        run: |
          sudo apt-get install libavcodec-dev libavfilter-dev libavformat-dev libfreetype6-dev

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake

        shell: bash
        working-directory: ${{runner.workspace}}/build

        run: |
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_WITH_TEST=ON -DBUILD_WITH_UBSAN=ON \
          -DBUILD_WITH_ASAN=ON -DBUILD_WITH_INSTALL=ON -DBUILD_WITH_COVERAGE=ON -DBUILD_OPT_BUILD_PACKAGES=ON \
          -DBUILD_MODULES=ON

      - name: Build-Core
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -C $BUILD_TYPE
